source :rubygems

gem 'rails', '~>2.3'
gem 'rspec', '~>1.3'
gem 'rspec-rails', '~>1.3'
gem 'mysql2', '~>0.2.0'
gem 'ruby-debug', :platforms => :ruby_18
gem 'test-unit', '~>1.2', :platforms => :ruby_19
gem 'database_cleaner'
gem 'andand'

gem 'edge_rider', :path => '../..'
