source 'https://rubygems.org'

gem 'rails', '~>4.1.0'
gem 'rspec'
gem 'rspec-rails'
gem 'mysql2'
gem 'rspec_candy'
gem 'ruby-debug', :platforms => :ruby_18
gem 'database_cleaner', '=1.0.1'
gem 'andand'
gem 'has_defaults'
gem 'minitest' # fix MiniTest deprecation warnings

gem 'edge_rider', :path => '../..'
