source :rubygems

gem 'rails', '~>3.0.17'
gem 'rspec'
gem 'rspec-rails'
gem 'mysql2', '~>0.2.0'
gem 'ruby-debug', :platforms => :ruby_18
gem 'database_cleaner'
gem 'andand'
gem 'has_defaults'

gem 'edge_rider', :path => '../..'
