---
name: Tests
'on':
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test_pg:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: "--health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5"
        ports:
        - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 2.7.4
          gemfile: Gemfile.6.1.pg
        - ruby: 3.2.1
          gemfile: Gemfile.6.1.pg
        - ruby: 2.7.4
          gemfile: Gemfile.7.0.pg
        - ruby: 2.7.4
          gemfile: Gemfile.7.1.pg
        - ruby: 3.2.1
          gemfile: Gemfile.7.0.pg
        - ruby: 3.2.1
          gemfile: Gemfile.8.0.pg
        - ruby: 3.3.6
          gemfile: Gemfile.7.0.pg
        - ruby: 3.3.6
          gemfile: Gemfile.7.1.pg
        - ruby: 3.3.6
          gemfile: Gemfile.7.2.pg
        - ruby: 3.3.6
          gemfile: Gemfile.8.0.pg
        - ruby: 3.4.1
          gemfile: Gemfile.7.1.pg
        - ruby: 3.4.1
          gemfile: Gemfile.7.2.pg
        - ruby: 3.4.1
          gemfile: Gemfile.8.0.pg
    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
    steps:
    - uses: actions/checkout@v2
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
    - name: Setup database
      run: |
        sudo apt-get install -y postgresql-client
        PGPASSWORD=postgres psql -c 'create database test;' -U postgres -p 5432 -h localhost
    - name: Bundle
      run: |
        gem install bundler:2.2.26
        bundle install --no-deployment
    - name: Run tests
      run: bundle exec rspec
